### PR TITLE
metric type changes

### PR DESCRIPTION
**Pull request by sushmarchandran**
Changed metric config with new changes as discussed.
Added keys is_counter and absent_value

### CODE REVIEW

**Comment by fabolive** [comment]
This PR should not be merged until the controller code refactoring is complete.

**Comment by fabolive** [comment]
This PR requires corresponding changes in the controller code to cache the config map in experiment objects.

**Comment by kalantar** [comment]
Validation check to be done by controller (cf: https://github.com/iter8-tools/iter8-analytics/issues/24)

- if is_counter = True, criterion_type = Delta, then throw an error. Check to be done on the controller end and the analytics service end.

**Comment by kalantar** [comment]
Added basic changes to read the metrics config map and to send to analytics server. To test with analytics server, need to use https://github.com/iter8-tools/iter8-analytics/pull/25.

**Comment by kalantar** [comment]
I've created https://github.com/iter8-tools/iter8-controller/issues/57 for the validation mentioned above; it can be done later. This is the minimal change to support the changes in the analytics server.

**Comment by kalantar** [comment]
@kimikowang or @fabolive could you review and verify that all the necessary changes have been made. I ran through the tutorial for istio.

**Pull request merged**
