### PR TITLE
Refactor code and use istio go-client

### PR DESCRIPTION
**Pull request by kimikowang**
0. Refactor code base
1. Support istio 1.4
2. Use istio go-client in managing istio rules
3. Upgrade controller-runtime and controller-tools
4. Skip Knative tests for now

### CODE REVIEW

**Comment by kalantar** [comment]
I ran the tutorial (expect the custom metric pat -- identified a problem with it not related this change). This seems to work.

**Comment by kalantar** [comment]
I realize I ran the tutorial with Istio 1.3.2, not Istio 1.4. @kimikowang can you confirm you successfully ran the tutorial with Istio 1.4?

**Comment by kimikowang** [comment]
> I realize I ran the tutorial with Istio 1.3.2, not Istio 1.4. @kimikowang can you confirm you successfully ran the tutorial with Istio 1.4?

Verified.

**Comment by kimikowang** [comment]
> I realize I ran the tutorial with Istio 1.3.2, not Istio 1.4. @kimikowang can you confirm you successfully ran the tutorial with Istio 1.4?

Verified.

**Pull request merged**
