### PR TITLE
Support for Istio telemetry v2

### PR DESCRIPTION
**Pull request by fabolive**
1. Created a new Grafana dashboard compatible with Istio telemetry-v2.
2. Changed the Helm chart to take the Istio telemetry version as a parameter so that query templates are created accordingly.
3. Created tutorial files compatible with Istio telemety-v2: latency is expressed in milliseconds.

### CODE REVIEW

**Comment by fabolive** [comment]
@sriumcp. @kalantar: 

When reviewing the new file `config/grafana/istio-telemetry-v2.json`, I recommend you check the diff with respect to `config/grafana/istio.json`.

Similarly, you should check the diff of the new tutorial files with respect to the corresponding existing files.

**Comment by fabolive** [comment]
This PR relates to 2 issues: #102 and #103.

**Comment by kalantar** [comment]
This PR looks good. Unless I install Istio 1.5, there isn't much I can do to test it. 
Are we updating our documentation as well? Perhaps we want to rename current things to "_telemenetry-v1" so that we can write documentation that uses an environment variable instead of separate commands?

**Comment by huang195** [comment]
@fabolive I guess this is the PR you mentioned in the scrum. I don't think this will impact Iter8-trend as I'm just taking the query template from an Experiment CR and re-run that query in Prometheus. So whatever changes to query template in Helm due to Istio telemetry version difference should just propagate to Iter8-trend.

**Pull request merged**
