### PR TITLE
increasing stepSize and decreasing iterations

### PR DESCRIPTION
**Pull request by huang195**

### CODE REVIEW

**Comment by kalantar** [comment]
@huang195 You've changed the files we also use for the tutorials. We need to either replicate these for the tests or replicate for the tutorials as separate things. Not sure the relative effort. Any thoughts?

@fabolive you're opinion?

**Comment by huang195** [comment]
I think we should keep them the same. The test cases are showing whatever we preach in our tutorials are actually working with the latest code. What is the reason to keep 2 different versions (I didn't quite catch the reason on the call).

**Comment by kalantar** [comment]
For the changes you have made, perhaps no reason. However, if we were to further modify to allow greater test coverage: some with cleanup, do pause, resume, delete a running experiment, etc. then we are doing different things. Our tutorials don't cover all these features because we were balancing features vs gaining basic understanding.

**Comment by huang195** [comment]
Fair enough, and I think it's important that we do these things. This PR is just to do what we discussed on the call - make current e2e tests a bit faster to lessen the time our developers wait for tests to complete. Testing time decreased from 22 minutes to 17 minutes, which is what I was expecting.

Regarding test coverage and additional functionalities such as pause and resume, we will need various code owners to decide and evaluate what is missing, so we can gradually add these in to improve our coverage. These are beyond the scope of the PR.

**Pull request closed without merging**
