### PR TITLE
fix prometheus query that breaks grafana dashboards

### LINKED ISSUE #75: Grafana not showing resource utilization graphs
Other than the top 3 windows, all the other Grafana windows are empty. See below

image

### PR DESCRIPTION
**Pull request by huang195**
fixed #75

### CODE REVIEW

**Comment by kalantar** [comment]
This change looks good to me. I don't know why the build is failing. I tried rerunning it; it still failed.

**Comment by kalantar** [comment]
@kimikowang is this because the PR is from a fork instead of a branch?

**Comment by fabolive** [comment]
> @kimikowang is this because the PR is from a fork instead of a branch?

Yes, @kalantar, that is the reason. I will merge it.

**Comment by huang195** [comment]
Oh sorry, didn't see we're supposed to create branches on the main repo instead of branches on a fork. Will keep that in mind in the future

**Comment by fabolive** [comment]
@huang195. No worries. We actually need to fix this. It has to do with a TravisCI limitation handling secrets. We will change how we run our tests to fix this issue.

**Pull request merged**
