### PR TITLE
Pause/Resume action

### PR DESCRIPTION
**Pull request by kimikowang**
1. Add action field to crd
2. Modify predicate to ignore unwanted events generated by update of cr 
3. Reorganize code in experiment types.

### CODE REVIEW

**Comment by kalantar** [comment]
@kimikowang can you help me understand why we want to use a different mechanism for rollforward/rollbackward and pause/resume? Is there a way to use the same crd feature and make its behavior clear(er)?

**Comment by kimikowang** [comment]
> @kimikowang can you help me understand why we want to use a different mechanism for rollforward/rollbackward and pause/resume? Is there a way to use the same crd feature and make its behavior clear(er)?

The `assessment` and `action` are handled in different places using different mechanism. This is the reason why I want to separate them. But yes we could merge them together in the same field.

**Comment by fabolive** [comment]
> > @kimikowang can you help me understand why we want to use a different mechanism for rollforward/rollbackward and pause/resume? Is there a way to use the same crd feature and make its behavior clear(er)?
> 
> The `assessment` and `action` are handled in different places using different mechanism. This is the reason why I want to separate them. But yes we could merge them together in the same field.

Right now, the field we use to indicate forced rollback and forced rollforward is called `assessment`. What would be a better name for a field whose values would refer to these 4 actions (pause/resume/override_failure/override_success)?

**Comment by fabolive** [comment]
> > > @kimikowang can you help me understand why we want to use a different mechanism for rollforward/rollbackward and pause/resume? Is there a way to use the same crd feature and make its behavior clear(er)?
> > 
> > 
> > The `assessment` and `action` are handled in different places using different mechanism. This is the reason why I want to separate them. But yes we could merge them together in the same field.
> 
> Right now, the field we use to indicate forced rollback and forced rollforward is called `assessment`. What would be a better name for a field whose values would refer to these 4 actions (pause/resume/override_failure/override_success)?

I guess `action` could work for all of them.

**Comment by fabolive** [comment]
@kalantar: The change in the field name will have implications for the Toolchain integration and perhaps the Tekton pipelines as well.

**Comment by kalantar** [comment]
> @kalantar: The change in the field name will have implications for the Toolchain integration and perhaps the Tekton pipelines as well.

Agreed.

**Comment by kalantar** [comment]
I think I would prefer just one entry in the crd. This simplifies it for users.

**Comment by kimikowang** [comment]
Need to re-design the logic. Close this right now.

**Pull request closed without merging**
